export const bsfMonsterLocations = {
  Zone1: {
    Normal: [
      {
        Monster: "Bozjan Nepenthes",
        Level: 1,
        Positions: [
          [15.7, 27.1],
          [17.4, 28.1],
          [17.4, 29.1],
          [16.3, 29.5],
        ],
      },
      {
        Monster: "Bozjan Orobon",
        Level: 1,
        Positions: [
          [17.5, 28.4],
          [18.3, 29.7],
          [19.5, 29.6],
          [19.0, 27.9],
        ],
      },
      {
        Monster: "Bozjan Korrigan",
        Level: 2,
        Positions: [
          [21.4, 27.1],
          [21.4, 25.8],
          [22.4, 25.8],
          [22.8, 26.3],
          [22.1, 27.5],
        ],
      },
      {
        Monster: "Bozjan Mudpuppy",
        Level: 2,
        Positions: [
          [21.3, 28.9],
          [20.8, 29.7],
          [21.1, 30.4],
          [22.7, 30.4],
          [22.8, 29.7],
          [22.4, 29.4],
        ],
      },
      {
        Monster: "Bozjan Matamata",
        Level: 3,
        Positions: [
          [30.3, 27.2],
          [30.5, 26.2],
          [31.2, 25.7],
          [32.1, 25.8],
          [32.7, 26.4],
          [32.3, 27.4],
          [31.8, 27.9],
        ],
      },
    ],
    Ashkin: [
      {
        Monster: "Bozjan Geshunpest",
        Level: 3,
        Positions: [[ 25.1  , 30.6 ],
          [ 24.3  , 28.8 ],
          [ 23.5  , 28.5 ],
          [ 23.0  , 30.2 ],],
        additionalInfo: "Night only",
      },
      {
        Monster: "Bozjan Wraith",
        Level: 5,
        Positions: [[ 33.9  , 26.3 ],
          [ 33.9  , 25.0 ],
          [ 34.7  , 24.5 ],
          [ 35.4  , 24.3 ],
          [ 36.2  , 24.7 ],
          [ 36.5  , 25.5 ],
          [ 36.5  , 26.5 ],
          [ 35.6  , 26.9 ],
          [ 34.5  , 27.0 ],],
        additionalInfo: "Night only",
      },
    ],
    Sprites: [
      {
        Monster: "Rain Sprite",
        Level: 4,
        Location: [32.83, 10.47],
        radius: 5000,
        additionalInfo: "Rain only",
      },
      {
        Monster: "Earth Sprite",
        Level: 2,
        Location: [32.82, 10.19],
        radius: 7500,
        additionalInfo: "Dust Storm only",
      },
      {
        Monster: "Wind Sprite",
        Level: 3,
        Location: [32.68, 10.4],
        radius: 4000,
        additionalInfo: "Gales only",
      },
      {
        Monster: "Lightning Sprite",
        Level: 5,
        Location: [32.63, 10.66],
        radius: 7500,
        additionalInfo: "Thunderstorm only",
      },
    ],
    Star: [
      {
        Monster: "Tideborn Angel",
        Level: "Star",
        Location: [32.58, 9.95],
      },
      {
        Monster: "Fern Flower",
        Level: "Star",
        Location: [32.83, 10.22],
      },
      {
        Monster: "Ink Claw",
        Level: "Star",
        Location: [32.7, 10.67],
      },
    ],
  },
  Zone2: {
    Normal: [
      {
        Monster: "Bozjan Doblyn",
        Level: 1,
        Location: [33.01, 10.35],
        radius: 4000,
      },
      {
        Monster: "Bozjan Sabotender",
        Level: 1,
        Location: [33.125, 10.4],
        radius: 5000,
      },
      {
        Monster: "Bozjan Tormentor",
        Level: 2,
        Location: [33.205, 10.27],
        radius: 5000,
      },
      {
        Monster: "Red Chocobo",
        Level: 2,
        Location: [33.21, 10.37],
        radius: 4000,
      },
      {
        Monster: "Bozjan Worm",
        Level: 3,
        Location: [33.033, 10.23],
        radius: 4000,
      },
      {
        Monster: "Bozjan Antlion",
        Level: 3,
        Location: [33.06, 10.08],
        radius: 5000,
      },
      {
        Monster: "Bozjan Bandersnatch",
        Level: 4,
        Location: [32.9, 10.12],
        radius: 4000,
      },
      {
        Monster: "Bozjan Biast",
        Level: 4,
        Location: [32.91, 9.961],
        radius: 5000,
      },
      {
        Monster: "Bozjan Taipan",
        Level: 4,
        Location: [32.85, 9.72],
        radius: 5000,
      },
    ],
    Ashkin: [
      {
        Monster: "Bozjan Wight",
        Level: 3,
        Location: [33.09, 10.17],
        radius: 4000,
        additionalInfo: "Night only",
      },
      {
        Monster: "Bozjan Dullahan",
        Level: 5,
        Location: [33.3, 10.53],
        radius: 5000,
        additionalInfo: "Night only",
      },
    ],
    Sprites: [
      {
        Monster: "Rain Sprite",
        Level: 2,
        Location: [33.03, 10.43],
        radius: 5000,
        additionalInfo: "Rain only",
      },
      {
        Monster: "Lightning Sprite",
        Level: 3,
        Location: [32.93, 10.27],
        radius: 3000,
        additionalInfo: "Thunderstorm only",
      },
      {
        Monster: "Wind Sprite",
        Level: 4,
        Location: [33.025, 10],
        radius: 5500,
        additionalInfo: "Gales only",
      },
      {
        Monster: "Earth Sprite",
        Level: 5,
        Location: [33.02, 9.74],
        radius: 5500,
        additionalInfo: "Dust Storm only",
      },
    ],
    Star: [
      {
        Monster: "Viy",
        Level: "Star",
        Location: [33.08, 10.35],
      },
      {
        Monster: "Psoglav",
        Level: "Star",
        Location: [33.16, 10.56],
      },
      {
        Monster: "Smok",
        Level: "Star",
        Location: [32.96, 9.7],
      },
    ],
  },
  Zone3: {
    Normal: [
      {
        Monster: "Bozjan Screamer",
        Level: 1,
        Location: [32.988, 9.496],
        radius: 5000,
      },
      {
        Monster: "Bozjan Elbst",
        Level: 1,
        Location: [33.1, 9.4],
        radius: 5000,
      },
      {
        Monster: "Bozjan Ranunculus",
        Level: 2,
        Location: [33.22, 9.4],
        radius: 5000,
      },
      {
        Monster: "Bozjan Phobosuchus",
        Level: 2,
        Location: [33.125, 9.54],
        radius: 5000,
      },
      {
        Monster: "Bozjan Ochu",
        Level: 3,
        Location: [33.24, 9.52],
        radius: 5500,
      },
      {
        Monster: "Bozjan Monitor",
        Level: 3,
        Location: [33.29, 9.855],
        radius: 5500,
      },
      {
        Monster: "Bozjan Snake",
        Level: 4,
        Location: [33.365, 9.57],
        radius: 5500,
      },
      {
        Monster: "Bozjan Goobbue",
        Level: 4,
        Location: [33.37, 9.9],
        radius: 3000,
      },
      {
        Monster: "Bozjan Elasmoth",
        Level: 5,
        Location: [33.28, 10.22],
        radius: 5000,
      },
      {
        Monster: "Bozjan Doll",
        Level: 5,
        Location: [33.36, 10.13],
        radius: 5000,
      },
      {
        Monster: "Bozjan Anzu",
        Level: 5,
        Location: [33.43, 10.06],
        radius: 5000,
      },
    ],
    Ashkin: [
      {
        Monster: "Bozjan Gravekeeper",
        Level: 3,
        Location: [33.2, 9.87],
        radius: 4000,
        additionalInfo: "Night only",
      },
      {
        Monster: "Bozjan Rider",
        Level: 5,
        Location: [33.32, 10.07],
        radius: 6000,
        additionalInfo: "Night only",
      },
    ],
    Sprites: [
      {
        Monster: "Lightning Sprite",
        Level: 2,
        Location: [33.23, 9.605],
        radius: 7500,
        additionalInfo: "Thunderstorm only",
      },
      {
        Monster: "Rain Sprite",
        Level: 3,
        Location: [33.13, 9.75],
        radius: 5500,
        additionalInfo: "Rain only",
      },
      {
        Monster: "Earth Sprite",
        Level: 4,
        Location: [33.14, 9.89],
        radius: 5000,
        additionalInfo: "Dust Storm only",
      },
      {
        Monster: "Wind Sprite",
        Level: 5,
        Location: [33.16, 10.05],
        radius: 5500,
        additionalInfo: "Gales only",
      },
    ],
    Star: [
      {
        Monster: "Bird of Barathrum",
        Level: "Star",
        Location: [33.4, 10.15],
      },
      {
        Monster: "Clingy Claire",
        Level: "Star",
        Location: [33.15, 9.83],
      },
      {
        Monster: "Patty",
        Level: "Star",
        Location: [33.15, 9.38],
      },
    ],
  },
};
